### ISSUE TITLE
How to map order_id

### ISSUE THREAD

**Issue by na0309111** [amimoto-ami/mauticommerce#2]
Just come up with order_id field which is not available from matching fields of Mautic. 

how to get order_id from woocommerce to mastic?

**Comment by hideokamoto** [comment]
Get WC_Order Object, and get the id.
https://docs.woothemes.com/wc-apidocs/class-WC_Order.html

Could you check server error log?
I think that this plugin failed to get order id by some error.

**Comment by na0309111** [comment]
Hi Hideokamoto,

Thank you for getting back to me, is there any possibility to update the plugin to get following extra fields?

- Order_id
- product ordered (name of products and quantity)
- Date of order

I have woocommerce install, where we provide them supply of 30 days and I want them to send them a reminder after 30 days to purchase again. 

We can only do that if we know when they purchased and how much product they purchase.

**Comment by Running-On-Empty** [comment]
When you ship them the 30 days supply just add the Lead to a 30 Day Delay Campaign that has a built in Wait period of 30 days.

At the end of the 30 days, remove the Lead from the 30 Day Delay Campaign.

Then re-add the Lead back into the 30 Day Delay Campaign to start the 30 day delay again.

Mautic is a one pass system, once a lead goes through a campaign the lead will no longer receive the emails.  You need to remove the lead and re-add it back to the campaign for the lead to get the next 30 Day Delay Campaign notification.  

CraigM

**Comment by hideokamoto** [comment]
I added filter to customize POST query.
You can add origin query.

Example)
```
add_filter( 'mauticommerce_query_mapping', 'add_mapping_query', 10, 2 );
function add_mapping_query( $query, $order ) {
        //Add $order Param to $query
        $query['customer_ip_address'] = $order->customer_ip_address;
        return $query;
}
```
