### ISSUE TITLE
Mautic receives 4 fields.

### ISSUE THREAD

**Issue by Running-On-Empty** [amimoto-ami/mauticommerce#3]
Mautic is getting only four fields:

City
Company
County
State

These are shown on the History tab on the Manage Leads option.  When I go into Edit the Lead only the Company and City fields are populated.

In the previous version no field in the Edit Lead area were populated.

I wish I knew more about PHP and could help.

**Comment by Running-On-Empty** [comment]
![mautic bridge form results](https://cloud.githubusercontent.com/assets/18452022/15075663/9c600a44-1373-11e6-8d67-a6ebf6674ae1.jpg)

**Comment by Running-On-Empty** [comment]
![mautic core](https://cloud.githubusercontent.com/assets/18452022/15075696/c74126d0-1373-11e6-8539-3cbae86dd3ad.jpg)

**Comment by hideokamoto** [comment]
Thanks for reporting.
It seems to be wrong mapping in this plugin.
Now I fix this issue.

Please wait a little while until updated.

**Comment by Running-On-Empty** [comment]
I just updated the your new version: Version 0.0.2.  Mautic is still not getting the leads information.  The results are the same as before.

This plugin is great, please do not get discouraged.  I am trying to help, I just don't know how to.

CraigM

**Comment by hideokamoto** [comment]
version 0.0.3 is supported to following issue.
https://github.com/amimoto-ami/mauticommerce/issues/2

If fix this issue, I notice here.
Regards.

**Comment by hideokamoto** [comment]
Hi!
I update the plugin and support to mapping country & state name.
Please update version0.1.0
If you find unmapped country & state, please notify me.

thanks.

**Comment by cremigerhonig** [comment]
mautic only receives mail, no other information
