### ISSUE TITLE
Unable to update plugin - must uninstall previous version to install new version.

### ISSUE THREAD

**Issue by Running-On-Empty** [amimoto-ami/mauticommerce#4]
I just tried to reinstall your great plugin over the previous version.  The message was that the directory already existed.  Then the install aborted.

I deactivated and uninstalled the previous version.  I then installed the new version.  The install went flawlessly.  It even had the correct directory for Mautic an the correct form number.

CraigM

**Comment by hideokamoto** [comment]
Oh sorry,
I forget to change plugin's version tag.
Please use version v0.0.3

https://wordpress.org/plugins/mauticommerce/
