### ISSUE TITLE
Wordpress.Org Documentation, I have created a sample.

### ISSUE THREAD

**Issue by Running-On-Empty** [amimoto-ami/mauticommerce#5]
I know you are working hard on this plugin.  I noticed on Wordpress.org your plugin does not have a good Description or Installation page.  I have created the sample pages below in an effort to help.  If you choose to you could give me access to the Wordpress.org documentation and I will keep it up to date.  Otherwise feel free to post the text below to WOrdpress.org as a start to document your great plugin.  My direct email is resourceful@gmail.com.

Craigm

Wordpress.org Mauticommerce Plugin

Description:
Mauticommerce is used to bridge user data from WooCommerce to the Mautic open source marketing automation system.  When your customer enters an order in Woocommerce, their contact data is used to create a new Mautic Lead.
This plugin is available through the official Wordpress.org Plugin Directory.  Simply download and install the plugin as you would any other plugin.
Mautic is a free open source marketing automation tool.  It can be downloaded at: www.mautic.org/download.  Mautic may or may not be installed before the Mauticommerce plugin.  You will need a functioning Mautic installation and a new Mautic Form for this plugin to work.

Installation:
You will need to create a Mautic form from within your Mautic installation.  Please add the following fields to the form: 
1.	address1 as a text field; 
2.	address2 as a text field; 
3.	city as a text field; 
4.	company as a text field; 
5.	country as a text field; 
6.	email as an email field; 
7.	firstname as a text field; 
8.	lastname as  a text field; 
9.	phone as a phone field; 
10.	zipcode as a text field; 
11.	state as a text field; and 
12.	order_id as a text field. 

Remember to Save & Close the form in Mautic.

Once you have created the form and saved it and note it’s Mautic Form ID (which can be found in the rightmost column on the general Forms page).  You will also need to know the directory where you installed Mautic (http://abc.net/Mautic/).

To set up this plugin, simply download it and install it into your Wordpress site.  Then go to the General Settings options of your Wordpress site.  Under Settings choose Mauticommerce.  Here you will find two fields for your Mautic URL and your Mautic Form ID which you recorded in the steps above.

That’s all there is to setting up Mauticommerce!
1.	Install the Mautic Commerce plugin
2.	Create a Mautic Form ID
3.	Enter the URL and Form ID into Mauticommerce under the Wordpress Setting page.
4.	Click “Save Changes” and you are done!

You will never need to visit this form again, your customers data will simply appear as a Lead in Mautic.

Now when a customer creates a new order in Woocommerce, their data will be sent to Mautic (through the Mautic Form you created).

**Comment by hideokamoto** [comment]
Thank you for creating many issues!  
I'd like to apply your readme issue to mine. 
Mind if I ask your WordPress.org's account? 
I'd like add you  to one of our contributor.

If you have any suggestions or request about this plugin, 
feel free create issues and pull request.

**Comment by Running-On-Empty** [comment]
My Wordpress.org account is 2craig.  I’ll be happy to contribute what I can.

 

Craigm

**Comment by hideokamoto** [comment]
Thanks!
I updated readme.txt and added contributor :)
https://wordpress.org/plugins/mauticommerce/
